platform:ios,'7.1'
pod 'MJRefresh', '~> 2.3.2'
pod 'SDWebImage', '~> 3.7.1'
pod 'AFNetworking', '~> 2.5.3'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'MJExtension', '~> 2.5.2'
pod 'Reachability', '~> 3.2'
pod 'Masonry', '~> 0.6.1'